export default [
  {
    id: 1,
    img: "./images/card-img1.jpg",
    rating: 5,
    reviewCount: 6,
    country: "USA",
    title: "Life lessons with katie",
    price: 136,
    openSpots: 0,
  },
  {
    id: 2,
    img: "./images/img2.jpg",
    rating: 4.5,
    reviewCount: 7,
    country: "India",
    title: "Sunflower",
    price: 90,
    openSpots: 1,
    location: "online",
  },
  {
    id: 3,
    img: "./images/img3.jpg",
    rating: 5.6,
    reviewCount: 10,
    country: "Indonesia",
    title: "stop war",
    price: 150,
    openSpots: 2,
  },
  {
    img: "./images/img2.jpg",
    rating: 4.5,
    reviewCount: 7,
    country: "India",
    title: "Sunflower",
    price: 90,
  },
  {
    img: "./images/img3.jpg",
    rating: 5.6,
    reviewCount: 10,
    country: "Indonesia",
    title: "stop war",
    price: 150,
  },
  {
    img: "./images/card-img1.jpg",
    rating: 5,
    reviewCount: 6,
    country: "USA",
    title: "Life lessons with katie",
    price: 136,
  },
];
